# Generated by Django 5.1.7 on 2025-03-12 19:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('IDFactura', models.AutoField(primary_key=True, serialize=False)),
                ('FechaFactura', models.DateField()),
                ('PuntoVenta', models.IntegerField()),
                ('NumFactura', models.IntegerField()),
                ('Dolar1', models.FloatField()),
                ('Dolar2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('IDProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('razonSocial', models.CharField(max_length=200)),
                ('cuit', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CUIT')),
                ('domicilio', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('IDDetalleFactura', models.AutoField(primary_key=True, serialize=False)),
                ('codigoInterno', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tasaiva', models.FloatField()),
                ('pesoscompra', models.FloatField()),
                ('dolarescompra', models.FloatField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('coef', models.FloatField()),
                ('IDFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricelist.factura')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='IDProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricelist.proveedor'),
        ),
    ]
